Repository webbuniv/Buweb, pull requests merged in 2024-06, with the labels that each got.

#14 Troy dev
  website/app/head.tsx
  website/app/layout.tsx
  website/app/page.tsx
  website/components/Footer/index.tsx
  website/package-lock.json
  website/package.json
  website/public/images/bugema.png
Labels: enhancement

#20 merge with default
  client/package.json
  client/src/App.js
  client/src/components/PrivateRoute/index.js
  client/src/context/AuthContext.js
  client/src/context/index.js
  client/src/examples/Navbars/DashboardNavbar/index.js
  client/src/examples/Navbars/DefaultNavbar/index.js
  client/src/index.js
  client/src/layouts/Slides/data/authorsTableData.js
  client/src/layouts/Slides/data/projectsTableData.js
  client/src/layouts/Slides/index.js
  client/src/layouts/authentication/sign-in/index.js
  client/src/layouts/tables/index.js
  client/src/routes.js
  client/src/state/index.js
  server/controllers/auth.js
  website/components/Header/ThemeToggler.tsx
  website/components/Header/index.tsx
  website/components/model/Model.tsx
  website/pnpm-lock.yaml
  website/styles/nav.css
Labels: enhancement

#36 syncing remote
  client/src/App.js
  client/src/components/FlexBetween/index.js
  client/src/components/Form/index.js
  client/src/components/PrivateRoute/index.js
  client/src/examples/Navbars/DashboardNavbar/index.js
  package-lock.json
  package.json
  website/components/Header/ThemeToggler.tsx
  website/components/Header/index.tsx
  website/components/model/Model.tsx
  website/package-lock.json
  website/package.json
  website/styles/index.css
  website/styles/nav.css
Labels: enhancement

#38 Troy dev
  website/components/Hero/index.tsx
  website/styles/index.css
Labels: enhancement

#49 merge
  client/src/layouts/tables/index.js
Labels: enhancement

#56 COMMIT
  server/index.js
Labels: API

#65 Daniel
  client/src/App.js
  client/src/layouts/authentication/sign-in/index.js
  client/src/layouts/events/index.js
  client/src/layouts/news/index.js
  client/src/layouts/publication/index.js
  server/controllers/events.js
  server/controllers/news.js
  server/controllers/publication.js
  server/models/Publication.js
  server/routes/news.js
  server/routes/publication.js
Labels: API, Dashboard

#72 sync
  website/components/Blog/index.tsx
  website/components/Common/SectionTitle.tsx
  website/components/Features/index.tsx
  website/components/Features/style.css
  website/public/images/features/bbb.jpg
  website/public/images/features/int.jpg
  website/public/images/features/post.jpg
  website/public/images/features/reg.jpg
Labels: enhancement

#74 Troy dev
  website/app/constants/news/index.tsx
  website/app/page.tsx
  website/components/Common/SectionTitle.tsx
  website/components/ExploreBugema/index.tsx
  website/components/Helper/Modal.tsx
  website/components/NewsCarousel/NewsCarousel.tsx
  website/components/Video/index.tsx
  website/utils/motion.tsx
Labels: enhancement

#75 move to production
  client/src/App.js
  client/src/layouts/authentication/sign-in/index.js
  client/src/layouts/events/index.js
  client/src/layouts/news/index.js
  client/src/layouts/publication/index.js
  client/src/layouts/tables/index.js
  server/controllers/events.js
  server/controllers/news.js
  server/controllers/publication.js
  server/models/Publication.js
  server/routes/news.js
  server/routes/publication.js
  website/app/constants/news/index.tsx
  website/app/page.tsx
  website/components/Blog/index.tsx
  website/components/Common/SectionTitle.tsx
  website/components/ExploreBugema/index.tsx
  website/components/Features/index.tsx
  website/components/Features/style.css
  website/components/Header/index.tsx
  website/components/Helper/Modal.tsx
  website/components/NewsCarousel/NewsCarousel.tsx
  website/components/Video/index.tsx
  website/components/model/Model.tsx
  website/public/images/features/bbb.jpg
  website/public/images/features/int.jpg
  website/public/images/features/post.jpg
  website/public/images/features/reg.jpg
  website/public/images/nav/burundi.jpg
  website/public/images/nav/nurses.jpg
  website/public/images/nav/palm-girls.jpg
  website/public/images/nav/palm-girls1.jpg
  website/styles/index.css
  website/styles/nav.css
  website/utils/motion.tsx
Labels: API, Website, Dashboard, Move to production

#100 sync
  server/controllers/news.js
  server/routes/events.js
  server/routes/news.js
  website/.env.example
  website/app/constants/news/index.tsx
  website/app/head.tsx
  website/app/page.tsx
  website/components/About/AboutSectionOne.tsx
  website/components/EventsandNews/EventsAndNews.tsx
  website/components/Header/ThemeToggler.tsx
  website/components/Header/index.tsx
  website/components/Header/menuData.tsx
  website/components/NewsCarousel/NewsCarousel.tsx
  website/components/model/Model.tsx
  website/package-lock.json
  website/types/types.ts
Labels: enhancement

#121 Move to production
  server/controllers/course.js
  server/controllers/department.js
  server/controllers/lecturer.js
  server/controllers/program.js
  server/controllers/school.js
  server/index.js
  server/models/Department.js
  server/models/Lecturer.js
  server/models/Program.js
  server/models/School.js
  server/routes/department.js
  server/routes/lecturer.js
  server/routes/program.js
  server/routes/school.js
Labels: API, Move to production

#128 Troy dev
  website/app/schools/school-of-agric/page.tsx
  website/app/schools/school-of-business/page.tsx
  website/app/schools/school-of-education/page.tsx
  website/app/schools/school-of-graduate/page.tsx
  website/app/schools/school-of-health/page.tsx
  website/app/schools/school-of-science/page.tsx
  website/app/schools/school-of-theology/page.tsx
Labels: Website

#139 Daniel
  website/components/Brands/index.tsx
  website/components/Features/index.tsx
  website/components/Header/ThemeToggler.tsx
  website/components/Header/index.tsx
  website/components/Hero/index.tsx
  website/components/model/Model.tsx
  website/components/model/Model1.tsx
  website/components/model/Model2.tsx
  website/components/model/Model3.tsx
  website/components/model/Model4.tsx
  website/styles/index.css
Labels: Website

#150 Move to production
  client/src/layouts/events/index.js
  client/src/layouts/news/index.js
  client/src/layouts/tables/index.js
  website/app/whybugema/page.tsx
  website/components/About/AboutSectionSix.tsx
  website/components/Common/Breadcrumb.tsx
  website/components/Events/SingleEvent.tsx
  website/components/model/Model.tsx
  website/components/model/Model1.tsx
Labels: API, Website, Dashboard, Move to production

#160 Move to production
  website/app/page.tsx
  website/components/About/AboutSectionSix.tsx
  website/components/Common/SectionTitle.tsx
  website/components/ExploreBugema/index.tsx
  website/components/Features/index.tsx
Labels: API, Website, Dashboard, Move to production

#174 Move to production
  website/app/studentlife/page.tsx
  website/components/About/AboutSectionLife.tsx
  website/components/About/AboutSectionLife2.tsx
  website/components/CampusNews/index.tsx
  website/components/Header/index.tsx
  website/components/Hero/index.tsx
  website/package-lock.json
  website/public/images/features/grad.jpg
  website/public/images/life/mind.jpg
  website/public/images/life/sport.jpg
Labels: API, Website, Dashboard, Move to production

#178 home page
  website/app/page.tsx
  website/components/Contact/NewsLatterBox.tsx
  website/components/Contact/index.tsx
  website/components/EventsandNews/EventsAndNews.tsx
  website/components/Header/index.tsx
  website/components/Hero/index.tsx
  website/components/HeroOverlay/HeroOverlay.tsx
  website/components/HeroVideo/HeroVideo.tsx
  website/components/Welcome/Welcome.tsx
  website/public/images/vc/vc-1.jpeg
  website/public/images/vc/vc-2.jpeg
  website/public/video/shape.svg
  website/public/video/video.jpg
  website/public/video/welcome.mp4
  website/styles/index.css
Labels: enhancement

#181 merge
  website/components/About/AboutSectionSeven.tsx
  website/components/Campuses/index.tsx
  website/components/ExploreBugema/index.tsx
  website/components/Footer/index.tsx
  website/components/Header/index.tsx
  website/components/model/Model4.tsx
  website/package-lock.json
  website/package.json
  website/public/images/features/banner.png
  website/public/images/footer/aerial1.png
  website/public/images/footer/aerial2.png
  website/public/images/footer/aerial2c.png
  website/public/images/footer/fooo.jpg
Labels: enhancement

#203 merge
  website/components/ExploreBugema/index.tsx
  website/components/Footer/index.tsx
  website/components/Header/index.tsx
  website/components/Hero/index.tsx
  website/components/HeroOverlay/HeroOverlay.tsx
  website/components/model/Model1.tsx
  website/components/model/Model2.tsx
  website/components/model/Model3.tsx
  website/components/model/Model4.tsx
  website/components/model/Model5.tsx
  website/styles/index.css
Labels: enhancement

#206 Move to production
  website/components/ExploreBugema/index.tsx
  website/components/Footer/index.tsx
  website/components/Header/index.tsx
  website/components/Hero/index.tsx
  website/components/HeroOverlay/HeroOverlay.tsx
  website/components/model/Model1.tsx
  website/components/model/Model2.tsx
  website/components/model/Model3.tsx
  website/components/model/Model4.tsx
  website/components/model/Model5.tsx
  website/next.config.js
  website/styles/index.css
Labels: API, Website, Dashboard, Move to production

#212 Merge
  website/components/Footer/index.tsx
  website/components/Header/index.tsx
  website/components/Hero/index.tsx
  website/next.config.js
Labels: enhancement

#220 mobile nav
  website/components/MobileNav/MobileNav.tsx
Labels: enhancement

#222 merge
  website/components/BelowHero/index.tsx
  website/components/Header/index.tsx
  website/components/Hero/index.tsx
  website/components/HeroOverlay/HeroOverlay.tsx
  website/components/model/Model.tsx
  website/components/model/Model1.tsx
  website/components/model/Model2.tsx
  website/components/model/Model3.tsx
  website/components/model/Model4.tsx
  website/components/model/Model5.tsx
  website/styles/index.css
Labels: enhancement

#227 Move to production
  client/src/layouts/events/index.js
  client/src/layouts/news/index.js
  server/controllers/events.js
  server/controllers/news.js
  server/models/Events.js
  server/models/News.js
  website/app/page.tsx
  website/components/BelowHero/index.tsx
  website/components/Blog/SingleBlog.tsx
  website/components/Header/index.tsx
  website/components/Hero/index.tsx
  website/components/HeroOverlay/HeroOverlay.tsx
  website/components/HeroVideo/HeroVideo.tsx
  website/components/MobileNav/MobileNav.tsx
  website/components/Schools/Schools.tsx
  website/components/Welcome/Welcome.tsx
  website/components/model/Model.tsx
  website/components/model/Model1.tsx
  website/components/model/Model2.tsx
  website/components/model/Model3.tsx
  website/components/model/Model4.tsx
  website/components/model/Model5.tsx
  website/styles/index.css
Labels: API, Website, Dashboard, Move to production

#229 merge
  client/src/layouts/events/index.js
  client/src/layouts/news/index.js
  server/controllers/events.js
  server/controllers/news.js
  server/models/Events.js
  server/models/News.js
  website/components/Blog/SingleBlog.tsx
  website/components/Header/index.tsx
Labels: enhancement

#236 Troy dev
  website/app/page.tsx
  website/components/Events/SingleEvent.tsx
  website/components/Events/index.tsx
  website/components/Hero/index.tsx
  website/components/MobileNav/MobileNav.tsx
  website/components/News/SingleNews.tsx
  website/components/News/index.tsx
  website/components/Schools/Schools.tsx
Labels: enhancement

#244 merge
  client/src/examples/Footer/index.js
  website/components/BelowHero/index.tsx
  website/components/Events/SingleEvent.tsx
  website/components/Header/index.tsx
  website/components/Hero/index.tsx
  website/components/Welcome/Welcome.tsx
  website/components/model/Model.tsx
  website/components/model/Model1.tsx
  website/components/model/Model2.tsx
  website/components/model/Model3.tsx
  website/components/model/Model4.tsx
  website/types/types.ts
Labels: enhancement

#245 Merge pull request #244 from webbuniv/staging
  website/components/CampusNews/index.tsx
  website/components/Events/SingleEvent.tsx
Labels: enhancement
